/**
 * Basemap styles for the mapcn map component (`components/ui/map.tsx`).
 *
 * OpenFreeMap's **Liberty** — free, keyless, no account. Chosen on 2026-08-28
 * over CARTO's Positron because the user asked for a map that shows real
 * places: Liberty draws the cafés, bars, restaurants and shops with icons and
 * their names from about zoom 16, and labels streets in English as well as
 * Hebrew. Positron is a "data" basemap and deliberately shows almost none of
 * that.
 *
 * Liberty has no dark twin, and running a different provider in dark mode
 * would mean different roads and Hebrew-only names when the theme flips, so
 * the dark style is Liberty with its own palette re-toned — generated by
 * `scripts/build-dark-basemap.mjs` (`npm run basemap:dark`) and served from
 * our own origin.
 */
export const MAP_STYLES = {
  light: "https://tiles.openfreemap.org/styles/liberty",
  dark: "/maplibre/liberty-dark.json",
} as const;

/**
 * The font the cluster counts are drawn in. MapLibre can only use a font the
 * *style's* glyph server actually has, so this has to move with MAP_STYLES:
 * Liberty serves Noto Sans, not the Open Sans mapcn ships with.
 */
export const CLUSTER_FONT = ["Noto Sans Bold"];

/**
 * MapLibre paints its own layers, so the pins can't be styled in CSS: these
 * are the palette values from globals.css, written out for the GL renderer.
 * `tests/unit/map-basemap.test.ts` fails if they drift from the stylesheet.
 *
 * `shades` runs small → large clusters; `on` is the count printed inside one,
 * and `ring` the outline drawn around it — the page's own ground colour, so a
 * pin reads as sitting on the app rather than on the tiles.
 */
export const MAP_COLORS = {
  light: {
    accent: "#2e7d5e",
    shades: ["#2e7d5e", "#256349", "#1a4635"] as [string, string, string],
    on: "#faf7f2",
    ring: "#faf7f2",
  },
  dark: {
    accent: "#c9a468",
    shades: ["#c9a468", "#b08c4f", "#96733a"] as [string, string, string],
    on: "#191613",
    ring: "#191613",
  },
} as const;

export const MAX_ZOOM = 18;

/**
 * Close enough to see what's around the room — Liberty starts naming cafés,
 * bars and shops at 16, which is the point of opening a room's map at all.
 */
export const ROOM_ZOOM = 16;

/** The whole country fits at this zoom on a phone. */
export const COUNTRY_ZOOM = 7;

/** Reads the theme the app is actually in (see `[data-theme]` in globals.css). */
export function currentTheme(): "light" | "dark" {
  if (typeof document === "undefined") return "light";
  const explicit = document.documentElement.getAttribute("data-theme");
  if (explicit === "dark" || explicit === "light") return explicit;
  return window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}
