import { chromium, devices } from "playwright";
const base = "https://nestup-kappa.vercel.app";
const browser = await chromium.launch();
const page = await (await browser.newContext({ ...devices["iPhone 13"] })).newPage();
await page.goto(base + "/login", { waitUntil: "networkidle" });
await page.fill('input[name="email"]', "nestup.tester@nestup.dev");
await page.fill('input[name="password"]', "Tester1234!");
await Promise.all([page.waitForURL((u) => !u.pathname.startsWith("/login"), { timeout: 60000 }), page.click('button[type="submit"]')]);
await page.goto(base + "/profile", { waitUntil: "networkidle" });
const table = page.getByRole("table", { name: "Daily life" });
await table.scrollIntoViewIfNeeded();
await table.screenshot({ path: "C:/Users/licht/AppData/Local/Temp/claude/C--Users-licht-OneDrive-UNIVERSITY-Year-B-Semester-B-FULL-STACK/82771dfa-5d42-44af-9523-3837fa038b88/scratchpad/daily_view_m.png" });
await browser.close();
