import { chromium } from "playwright";
const base = "https://nestup-kappa.vercel.app";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1440, height: 1000 } })).newPage();
await page.goto(`${base}/login`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(1500);
await page.locator('input[type="email"]').fill("seed.user838@nestup.dev");
await page.locator('input[type="password"]').fill("Demo1234!");
await page.getByRole("button", { name: /sign in|log in/i }).first().click();
await page.waitForTimeout(4000);
await page.goto(`${base}/profile/edit`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(3000);
const sel = page.locator('select[name="pref_safe_room"]');
await sel.scrollIntoViewIfNeeded();
await page.waitForTimeout(600);
const box = await sel.boundingBox();
await page.screenshot({ path: "mamad-profile.png", clip: { x: Math.max(0, box.x - 700), y: Math.max(0, box.y - 190), width: 1100, height: 330 } });
console.log("shot taken; value:", await sel.inputValue());
await browser.close();
