import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "vitest";
import { CLUSTER_FONT, MAP_COLORS, MAP_STYLES } from "@/components/map/basemap";

const css = readFileSync(join(import.meta.dirname, "../../app/globals.css"), "utf8");

/** Pulls one custom property out of a block of globals.css. */
function token(block: string, name: string): string {
  const start = css.indexOf(block);
  expect(start, `${block} not found in globals.css`).toBeGreaterThan(-1);
  const scope = css.slice(start, css.indexOf("}", start));
  return new RegExp(`--${name}:\s*([^;]+);`).exec(scope)?.[1].trim() ?? "";
}

describe("map colours", () => {
  // MapLibre paints in WebGL, so these hexes are copies of the stylesheet's
  // rather than reads of it. Copies drift; this is the thing that notices.
  test("match the palette in globals.css", () => {
    expect(MAP_COLORS.light.accent).toBe(token(":root {", "accent"));
    expect(MAP_COLORS.light.on).toBe(token(":root {", "accent-contrast"));
    expect(MAP_COLORS.light.ring).toBe(token(":root {", "paper"));
    expect(MAP_COLORS.dark.accent).toBe(token('[data-theme="dark"] {', "accent"));
    expect(MAP_COLORS.dark.on).toBe(token('[data-theme="dark"] {', "accent-contrast"));
    expect(MAP_COLORS.dark.ring).toBe(token('[data-theme="dark"] {', "paper"));
  });

  test("cluster shades start at the accent and only get deeper", () => {
    for (const theme of ["light", "dark"] as const) {
      const shades = MAP_COLORS[theme].shades;
      expect(shades[0]).toBe(MAP_COLORS[theme].accent);
      expect(new Set(shades).size).toBe(3);
      for (const shade of shades) expect(shade).toMatch(/^#[0-9a-f]{6}$/);
    }
  });
});

test("both basemaps are keyless, and the dark one is served by us", () => {
  // Liberty is the style that names cafés and shops; its dark twin is
  // generated by scripts/build-dark-basemap.mjs into public/maplibre.
  expect(MAP_STYLES.light).toBe("https://tiles.openfreemap.org/styles/liberty");
  expect(MAP_STYLES.dark).toBe("/maplibre/liberty-dark.json");
  for (const url of Object.values(MAP_STYLES)) {
    expect(url).not.toMatch(/api[_-]?key|access[_-]?token/i);
  }
});

test("the dark style really was generated, and keeps Liberty's places", () => {
  const dark = JSON.parse(
    readFileSync(join(import.meta.dirname, "../../public/maplibre/liberty-dark.json"), "utf8")
  ) as { layers: { id: string; paint?: Record<string, unknown> }[]; glyphs: string };
  // The POI layers are the whole point of the swap — losing them in dark mode
  // would quietly undo it.
  expect(dark.layers.filter((l) => /^poi/.test(l.id)).length).toBeGreaterThan(2);
  // Labels have to be light ink, or they vanish against the re-toned ground.
  const labels = dark.layers.filter((l) => l.paint?.["text-color"]);
  expect(labels.length).toBeGreaterThan(5);
  for (const layer of labels) expect(layer.paint!["text-color"]).toBe("#e7e1d7");
  // Cluster counts are drawn in CLUSTER_FONT, which only exists on this
  // style's glyph server.
  expect(dark.glyphs).toContain("openfreemap.org");
  expect(CLUSTER_FONT).toEqual(["Noto Sans Bold"]);
});
